### ISSUE TITLE
while install the composer the following exception is come from the app

### ISSUE THREAD

**Issue by arman9189** [Mahanteshkumbar/Laravel7.x-Roles-Permissions-Admin-Paper-Dashboard-bootstrap4#1]
InvalidArgumentException

  Please provide a valid cache path.

  at C:\laragon\www\bgbnew\vendor\laravel\framework\src\Illuminate\View\Compiler                                                                                                                s\Compiler.php:36
    32|      */
    33|     public function __construct(Filesystem $files, $cachePath)
    34|     {
    35|         if (! $cachePath) {
  > 36|             throw new InvalidArgumentException('Please provide a valid c                                                                                                                ache path.');
    37|         }
    38|
    39|         $this->files = $files;
    40|         $this->cachePath = $cachePath;

  1   C:\laragon\www\bgbnew\vendor\laravel\framework\src\Illuminate\View\ViewSer                                                                                                                viceProvider.php:91
      Illuminate\View\Compilers\Compiler::__construct(Object(Illuminate\Filesyst                                                                                                                em\Filesystem))

  2   C:\laragon\www\bgbnew\vendor\laravel\framework\src\Illuminate\Container\Co                                                                                                                ntainer.php:801
      Illuminate\View\ViewServiceProvider::Illuminate\View\{closure}(Object(Illu                                                                                                                minate\Foundation\Application), [])
Script @php artisan package:discover --ansi handling the post-autoload-dump even                                                                                                                t returned with error code 1

**Comment by Mahanteshkumbar** [comment]
pull the latest commit. Updated project with missing storage folder
run
php artisan config:cache

**Latest commit**
#1 0c003e96095b11d3247f46904ab61c2d9d2402da

**Comment by Mahanteshkumbar** [comment]
Closed
